config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  resources :articles

   root 'welcome#index'

end

app/models/article.rb
class Article < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	def index
		@articles = Article.all
	end
	def show
	  @article = Article.find(params[:id])
	end
	def new
		@article = Article.new
	end
	def create
		@article = Article.new(params.require(:article).permit(:title, :text))

		@article.save
		redirect_to article_path(@article)
	end


end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_form.html.erb
<%= form_for(@article) do |f| %>
<p>
	<%= f.label :Title %> </br>
	<%= f.text_field :title %>
</p>
<p>
	<%= f.label :Description %> </br>
	<%= f.text_area :text %>
</p>
<p>
	<%= f.submit %>
</p>
<% end %>

app/views/articles/index.html.erb
<h1> Article Blog </h1>
<h2> Article Lists </h2>
<ul>
<% @articles.each do |article| %>
  <li><%= link_to article.title,article_path(article) %></li>
  <% end %>
</ul></br>
<%= link_to "create a new Article", new_article_path %>

app/views/articles/new.html.erb
<%= render partial: 'form' %>

app/views/articles/show.html.erb
<h1><%= @article.title %></h1>
<p> <%= @article.text %></p>
<%= link_to "<< Back to Articles List", articles_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blogapp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/welcome/index.html.erb
<h1>Welcome to  Rails App !</h1>
<%= link_to "Blog App", articles_path %>